/* tslint:disable */
/* eslint-disable */
/**
 * TaskManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserModel } from './user-model';
 /**
 * 
 *
 * @export
 * @interface Comment
 */
export interface Comment {

    /**
     * @type {string}
     * @memberof Comment
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Comment
     */
    productId?: string;

    /**
     * @type {UserModel}
     * @memberof Comment
     */
    author?: UserModel;

    /**
     * @type {string}
     * @memberof Comment
     */
    content?: string | null;

    /**
     * @type {Date}
     * @memberof Comment
     */
    createdAt?: Date;
}
