/* tslint:disable */
/* eslint-disable */
/**
 * TaskManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateProductScheme
 */
export interface CreateProductScheme {

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof CreateProductScheme
     */
    price?: number;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    model?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    brand?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    processor?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    gpu?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    displayResolution?: string | null;

    /**
     * @type {number}
     * @memberof CreateProductScheme
     */
    displayDiagonal?: number;

    /**
     * @type {number}
     * @memberof CreateProductScheme
     */
    refreshRate?: number;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    displayType?: string | null;

    /**
     * @type {number}
     * @memberof CreateProductScheme
     */
    ssdCapacity?: number;

    /**
     * @type {number}
     * @memberof CreateProductScheme
     */
    ramCapacity?: number;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    operatingSystem?: string | null;

    /**
     * @type {string}
     * @memberof CreateProductScheme
     */
    fileId?: string;
}
