/* tslint:disable */
/* eslint-disable */
/**
 * TaskManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Comment } from './comment';
import { FileModel } from './file-model';
 /**
 * 
 *
 * @export
 * @interface Product
 */
export interface Product {

    /**
     * @type {string}
     * @memberof Product
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Product
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof Product
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof Product
     */
    price?: number;

    /**
     * @type {string}
     * @memberof Product
     */
    model?: string | null;

    /**
     * @type {string}
     * @memberof Product
     */
    brand?: string | null;

    /**
     * @type {string}
     * @memberof Product
     */
    processor?: string | null;

    /**
     * @type {string}
     * @memberof Product
     */
    gpu?: string | null;

    /**
     * @type {string}
     * @memberof Product
     */
    displayResolution?: string | null;

    /**
     * @type {number}
     * @memberof Product
     */
    displayDiagonal?: number;

    /**
     * @type {number}
     * @memberof Product
     */
    refreshRate?: number;

    /**
     * @type {string}
     * @memberof Product
     */
    displayType?: string | null;

    /**
     * @type {number}
     * @memberof Product
     */
    ssdCapacity?: number;

    /**
     * @type {number}
     * @memberof Product
     */
    ramCapacity?: number;

    /**
     * @type {string}
     * @memberof Product
     */
    operatingSystem?: string | null;

    /**
     * @type {FileModel}
     * @memberof Product
     */
    photo?: FileModel;

    /**
     * @type {Array<Comment>}
     * @memberof Product
     */
    comments?: Array<Comment> | null;
}
